version: '3.8'

services:
  node-template:
    image: harbor.internal.codebuckets.in/node-template/stage
    container_name: node-template
    restart: unless-stopped
    ports:
      - "127.0.0.1:25000:3000"
    networks:
      - database_network
    env_file:
      - /home/empty.env

networks:
  database_network:
    external: true
